services:
  cs16-tournament:
    image: kuteki/cs1.6-rehlds:1.3
    container_name: cs1.6-rehlds
    network_mode: "host"
    environment:
      - MAP=de_shortdust2
      - MAXPLAYERS=8
      - TICKRATE=1000
    volumes:
      - ./config/server.cfg:/home/steam/hlds/cstrike/server.cfg
      - ./config/maps:/home/steam/hlds/cstrike/maps
      - ./config/reunion.cfg:/home/steam/hlds/cstrike/reunion.cfg
      
      - ./config/whblocker.ini:/home/steam/hlds/cstrike/addons/whblocker/config.ini
      
      - ./config/amxmodx:/home/steam/hlds/cstrike/addons/amxmodx/configs

      #- ./config/BotProfile.db:/home/steam/hlds/cstrike/BotProfile.db
      #- ./config/BotChatter.db:/home/steam/hlds/cstrike/BotChatter.db

      - ./config/matchbot_config:/home/steam/hlds/cstrike/addons/matchbot/cfg:ro
      - ./config/maplist.txt:/home/steam/hlds/cstrike/addons/matchbot/maplist.txt:ro
    stdin_open: true
    tty: true
    restart: unless-stopped

  fastdl:
    image: nginx:alpine
    container_name: cs16-fastdl
    ports:
      - "80:80"
    volumes:
      - ./config/maps:/usr/share/nginx/html/maps:ro
      - ./config/overviews:/usr/share/nginx/html/overviews:ro
    restart: unless-stopped