[AIMBOT]
; Detectarea AimBot ON/OFF (0 | 1)
AIM_DETECTION = 1

; Sensibilitatea de detectie a AimBot (0 | 10)
;SENS = 8

; Avertismente multiple pentru fiecare verificare [dezactivati pentru DeathMatch] (0 | 1)
MULTI_WARN = 1

; Numarul de avertismente inainte de a notifica adminii pe chat (0 | 50)
NOTIFY_WARNS = 3

; Numarul maxim de avertismente inainte de detectarea AimBot (2 | 50)
MAX_WARNS = 5

; Numarul de screenshoturi curate dupa care se reseteaza avertismentele (5 | 1000)
SHOTS_RESET = 40

; Resetarea avertismentelor dupa "n" kill-uri (10 | 500)
KILLS_RESET = 35

; Resetarea avertismentelor dupa "n" secunde de la ultimul avertisment (30 | 1800)
TIME_RESET = 420

[NOSPREAD]
; Activarea detectiei NoSpread ON/OFF (0 | 1)
NOSPREAD_DETECTION = 1

; Numarul de avertismente inainte de a notifica adminii pe chat (15 | 300)
NOTIFY_WARNS = 15

; Numarul maxim de avertismente inainte de detectarea NoSpread (25 | 300)
MAX_WARNS = 40

[PUNISH]
; Motivul pentru ban la detectarea AimBot
REASON_AIMBOT = Aim Detected

; Timpul pentru ban la detectarea AimBot
BAN_TIME_AIMBOT = 43200

; Motivul pentru ban la detectarea NoSpread
REASON_NOSPREAD = NoSpread Detected

; Timpul pentru ban la detectarea NoSpread
BAN_TIME_NOSPREAD = 43200

; Parametri pentru comanda de ban:
; [time] - timpul banului
; [userid] - userid-ul jucatorului banat
; [steam] - SteamID-ul jucatorului banat
; [ip] - IP-ul jucatorului banat
; [reason] - motivul pentru ban

; Comanda folosita pentru banarea automata la detectarea AimBot (Maxim 127 de caractere)
PUNISH_AIMBOT = amx_ban [time] [userid] [reason]

; Comanda folosita pentru banarea automata la detectarea NoSpread (Maxim 127 de caractere)
PUNISH_NOSPREAD = amx_ban [time] [userid] [reason]

[SAVE]
; Modul de salvare al avertismentelor la reconectarea jucatorilor (0 | 3)
; 0 - dezactivat | 1 - pe SteamID | 2 - pe IP | 3 - pe SteamID sau IP
TYPE = 2

; Numarul minim de avertismente salvate pentru detectarea AimBot (2 | 50)
AIM_WARNS = 2

; Numarul minim de avertismente salvate pentru detectarea NoSpread (15 | 300)
NOSPREAD_WARNS = 15

[OTHER]
; Adminii care au acces sa vada notificarile pentru detectarea AimBot sau NoSpread
; se introduc flag-urile de acces (default: d) 
FLAG_ALERT = d

; Activati Protectia la Trimiterea Armelor ON/OFF (0 | 1)
SEND_PROTECTION_WEAPON = 0
